### PR TITLE
Licenses, spell checking and a bit more explanations

### PR DESCRIPTION
**Pull request by MargaretDuff**
## Describe your contribution

A really interesting notebook - thank-you!

I have currently:
- Added licenses
- Added some headings and text to make it a bit more readable

Have put a draft pull request in. Before we merge I will run the notebook overnight (it takes a long time!). Can you also let me know where the image of the glass tubes in the metal container came from? 

## Checklist when you are ready to request a review

- [ ] I have performed a self-review of my code
- [ ] I have created a new folder, containing my contributions which are in the form of jupyter notebooks, with any necessary supporting python files, and a LICENSE file.
- [ ] I have added a description of my contribution(s) to the top of my file(s)
- [ ] If publicly available, I have added a link to the dataset used near the top of my file(s)
- [ ] I have added the CIL version I ran with near the top of my file(s)
- [ ] The content of this Pull Request (the Contribution) is intentionally submitted for inclusion in CIL-User-Showcase.
- [ ] I confirm that the contribution does not violate any intellectual property rights of third parties.
- [ ] I confirm that I have added license headers to all of the files I am contributing (with a license of my choice)
- [ ] Change pull request label to 'Waiting for review' 

Note: for an example of a contribution, where a license header, description, data link and CIL version has been added, please
see: [example_contribution](https://github.com/TomographicImaging/CIL-User-Showcase/blob/main/example_contribution)

### CODE REVIEW

**Comment by MargaretDuff** [comment]
Hi @IdaPug - I have run the notebook overnight and added some more explanations to the L2 TV example. Let me know what you think!

**Comment by IdaPug** [comment]
The changes looks good!

**Comment by lauramurgatroyd** [comment]
I just updated to use CIL 23.1.0 and add a summary at the end comparing the different reconstructions.

With v23.0.1 it took me 200mins to run the notebook, whereas now with v23.1.0 it only takes me 35mins!

**Review by jakobsj — CHANGES_REQUESTED** [review]
Looks great - a few comments mainly on the maths (due to size of notebook I am not given the option to comment on individual lines it seems):
- In the second paragraph under the notebook title it says 4 recon methods, but I only see 3 listed. Change to 3?  Maybe put each recon method on separate bullet?
- For showing reconstructed images from the difrerent methods, such as output cell [12] and [15], I'd suggest showing a couple of slices/channels to see any differences and to remind the reader that this is hyperspectral.

In the maths for the tikhonov in energy and TV in space method a couple of edits are needed:
- Nabla_energy makes sense since derivate wrt "energy", but "x_spatial" does not make sense.  Similarly to Nabla_energy, it should probably be TV_spatial or TV_(x1,x2) or similar.
- Currently x is used both as the unknown image to be determined and in x0, x1, x2 for spectral and spatial dimension names. This is unclear and should be changed.  I recommend using "u" for the unknown image to keep x0, x1, x2 free for dimension names.  In CIL we also use label names for these dimension names, so could consider instead sth like TV_(horizontal_x, horizontal_y).  This also includes "x" in "horizontal_x", so doesn't fully solve the inconsistency - really suggest to use say "u" throughout the notebook for the image. I'd suggest keeping to x0, x1, x2.
- The grad2 operator returns the spectral dimension first, then the two spatial together. To be consistent with this, the optimization problem above the grad2 line should have the tikhonov and tv terms swapped. This is also consistent with the order of the terms in the final f(K(x)) equation.
- The block operator K and A should not be mathcal font.
- The grad2 equation should be edited to use a symbol such as D instead of "Grad2" and no parenthesis around the image
```math
D u = \left[ \begin{array}{c} D_{x_0} u \\ D_{(x_1,x_2)} u \end{array} \right]  = \left[ \begin{array}{c} D_{x_0} u \\ \left[ \begin{array}{c} D_{x_1} u \\ D_{x_2} u \end{array}\right]  \end{array} \right]
```
- Replace "splitTik_TV" by symbol in math

**Comment by MargaretDuff** [comment]
Thanks @Jakob - I think my updates covered all your points. If you are happy we will ask Ida to merge it

**Review by jakobsj — CHANGES_REQUESTED** [review]
Changes look great @MargaretDuff, thanks!  Two additional comments:
- The very first and very late energy channels are very noisy and not really representative and the reconstructions for those channels look fairly bad. COuld you update to some that are within the more regular part of the spetrum, perhaps 20 or 30, 63 and 90 or 100?  Sorry for not being specific in my suggestion on adding channel images.
- I think it would make sense to update the variable names in the code to match the renamed math, e.g. D instead of Grad2 and h instead of splitTikh_TV.

**Comment by MargaretDuff** [comment]
Thanks @Jakob - went for 40,60 and 80 - shows some different brightness but nice reconstructions. Have updated the variable names and reran the notebook

**Review by jakobsj — APPROVED** [review]
Brilliant @MargaretDuff, looks great with the updated channels!

**Comment by MargaretDuff** [comment]
Thanks @jakobsj! @IdaPug - Please could you approve this pull request and then we will approve your pull request to the CIL user notebooks repository

**Review by IdaPug — APPROVED** [review]

**Pull request merged**
